#!/bin/bash
#PBS -q normal
#PBS -l mem=64Gb
#PBS -l walltime=1:00:00
#PBS -l jobfs=400GB
#PBS -l ncpus=8
#PBS -l wd
#PBS -l storage=gdata/hh5+gdata/ik11

module purge
module use /g/data/hh5/public/modules
module load conda/analysis3
module load esmf

GRIDDIR='/g/data/ik11/inputs/access-om3/0.x.0/025deg/mom'
ln -sf $GRIDDIR/ocean_hgrid.nc ocean_hgrid.nc
ln -sf $GRIDDIR/ocean_vgrid.nc ocean_vgrid.nc

PATH=../ocean-ic/:$PATH
echo $PATH

for((i=1; i<=12; i++))
do
printf -v mon "%02d"  "${i}"
echo /g/data/ik11/inputs/access-om3/woa23/monthly/woa23_decav_ts_"${mon}"_04.nc
ln -sf /g/data/ik11/inputs/access-om3/woa23/monthly/woa23_decav_ts_"${mon}"_04.nc input.nc

mkdir -p /g/data/ik11/inputs/access-om3/woa23/025
makeic.py --use_mpi WOA input.nc input.nc input.nc input.nc MOM ocean_hgrid.nc ocean_vgrid.nc /g/data/ik11/inputs/access-om3/woa23/025/woa23_ts_"${mon}"_mom025.nc
done
